### ISSUE TITLE
truncated unicode strings

### ISSUE THREAD

**Issue by odanoburu** [OAB-exams/oab-exam-parser#1]
shows unicode points in output `&#127` instead of unicode character.

**Comment by odanoburu** [comment]
these are actually numeric entities and are part of the XML spec. one can use pipe output through `xmllint --format` to remove them. I did not find a way of not producing them with the `xmlgen` library,

**Comment by arademaker** [comment]
Please add instructions how to pre and post processing the parser

**Comment by odanoburu** [comment]
```sh
oab-exam xml 2010-01.txt | xmllint --format > 2010-01.xml
```
vou colocar no README tb!
